pub use crate::prelude::*;
use crate::{
    ast::{
        resolved_variable::{ResolvedVariable, VariableId},
        spanned::Spanned,
        type_expressions::TypeExpression,
    },
    core_compiler::{
        shared_value_tracking::SharedValueTracking,
        to_instructions::{InstructionContext, ToInstructions},
    },
    global::{
        operators::{
            ArithmeticUnaryOperator, BinaryOperator, ComparisonOperator,
            UnaryOperator, modification::ModificationOperator,
        },
        root_properties::RootProperty,
        stack_index::StackIndex,
    },
    instruction::regular_instruction::RegularInstruction,
    libs::core::core_lib_id::CoreLibId,
    shared_values::{
        PointerAddress, ReferenceMutability, SelfOwnedPointerAddress,
        SharedContainerMutability,
    },
    types::{
        r#type::Type, type_definition::callable::CallableKind,
        type_definition_with_metadata::LocalReferenceMutability,
    },
    values::{
        core_value::CoreValue,
        core_values::{
            self, Instant,
            boolean::Boolean,
            decimal::{Decimal, typed_decimal::TypedDecimal},
            endpoint::Endpoint,
            integer::{Integer, typed_integer::TypedInteger},
            text::Text,
        },
        value::Value,
        value_container::ValueContainer,
    },
};
use core::{
    fmt::Display,
    ops::{self, Neg},
    str::FromStr,
};

#[derive(Clone, Debug)]
/// An expression in the AST
pub struct DatexExpression {
    pub data: Box<DatexExpressionData>,
    pub span: ops::Range<usize>,
    pub ty: Option<Type>,
}
impl Default for DatexExpression {
    fn default() -> Self {
        DatexExpression {
            data: Box::new(DatexExpressionData::Statements(Statements {
                statements: Vec::new(),
                is_terminated: false,
                unbounded: None,
            })),
            span: 0..0,
            ty: None,
        }
    }
}
impl DatexExpression {
    pub fn new(data: DatexExpressionData, span: ops::Range<usize>) -> Self {
        DatexExpression {
            data: Box::new(data),
            span,
            ty: None,
        }
    }

    pub fn data(&self) -> &DatexExpressionData {
        &self.data
    }

    pub fn data_mut(&mut self) -> &mut DatexExpressionData {
        &mut self.data
    }

    pub fn span(&self) -> &ops::Range<usize> {
        &self.span
    }

    pub fn ty(&self) -> Option<&Type> {
        self.ty.as_ref()
    }
}

// PartialEquality for DatexExpression ignores the span (allows for easier testing)
impl PartialEq for DatexExpression {
    fn eq(&self, other: &Self) -> bool {
        self.data == other.data
    }
}

#[derive(Clone, Debug, PartialEq)]
/// The different kinds of type expressions in the AST
#[derive(Default)]
pub enum DatexExpressionData {
    /// This is a marker for recovery from parse errors.
    /// We should never use this manually.
    #[default]
    Noop,

    Recover,
    NativeImplementationIndicator,

    /// null
    Null,

    /// (...)
    OmitRecursive,

    /// Boolean (true or false)
    Boolean(Boolean),
    /// Text, e.g "Hello, world!"
    Text(Text),
    /// Decimal, e.g 123.456789123456
    Decimal(Decimal),

    /// Typed Decimal, e.g. 123.456i8
    TypedDecimal(TypedDecimal),

    /// Integer, e.g 123456789123456789
    Integer(Integer),

    /// DateTime, e.g. 2026-04-13T18:28:09.415Z (stored as Instant)
    Instant(Instant),

    Range(RangeDeclaration),

    /// Typed Integer, e.g. 123i8
    TypedInteger(TypedInteger),

    /// Identifier (variable / core type usage)
    Identifier(String),

    /// Endpoint, e.g. @test_a or @test_b
    Endpoint(Endpoint),
    /// List, e.g  `[1, 2, 3, "text"]`
    List(List),
    /// Map, e.g {"xy": 2, (3): 4, xy: "xy"}
    Map(Map),
    /// One or more statements, e.g (1; 2; 3)
    Statements(Statements),
    /// reference access to shared value, e.g. '$ABC / 'mut $ABC
    RequestSharedRef(RequestSharedRef),

    /// move a shared value, e.g. $ABC
    MoveSharedValue(SelfOwnedPointerAddress),

    ResolveCoreLibId(CoreLibId),

    /// compile ( ... )
    Compile(CompileExpression),

    /// Conditional expression, e.g. if (true) { 1 } else { 2 }
    Conditional(Conditional),

    // TODO #611: Give information on type kind (nominal & structural)
    /// Variable declaration, e.g. const x = 1, const mut x = 1, or var y = 2. VariableId is always set to 0 by the ast parser.
    VariableDeclaration(VariableDeclaration),
    /// Variable assignment, e.g. x = 42 or y += 1
    VariableAssignment(VariableAssignment),
    /// Variable access - only generated by the precompiler, not by the parser
    VariableAccess(VariableAccess),

    // TODO #612: Shall we avoid hoisting for type aliases?
    // This would remove the ability to have recursive type
    // definitions.
    /// Type declaration, e.g. type MyType = { x: 42, y: "John" };
    TypeDeclaration(TypeDeclarationExpression),

    /// Entity declaration, e.g. entity MyEntity = { x: 42, y: "John" };
    EntityDeclaration(EntityDeclarationExpression),

    /// Type expression, e.g. type(1 | 2)
    TypeExpression(TypeExpression),

    /// callable (function/procedure) declaration, e.g. function my_function() -> type ( ... )
    CallableDeclaration(CallableDeclaration),

    /// Create a new shared container
    CreateShared(CreateShared),
    /// Create a new reference
    DeriveRef(DeriveRef),

    /// Derive a new shared reference
    DeriveSharedRef(DeriveSharedRef),

    /// Creates a new mutable value
    CreateMut(CreateMut),

    /// Unbox
    Unbox(Unbox),

    /// Clone
    Clone(CloneExpression),

    /// relative StackIndex, e.g. \0, \1, \2, ...
    StackIndex(StackIndex),

    /// Tag, e.g. #Variant1
    Tag(TagExpression),

    /// Property access on the root, e.g. $.print
    RootPropertyAccess(RootPropertyAccess),

    /// Stack assignment e.g. {0} = ...
    StackAssignment(StackAssignment),

    /// Push list to stack, e.g. {...} = ...
    StackListAssignment(StackListAssignment),

    /// Binary operation, e.g. x + y
    BinaryOperation(BinaryOperation),

    /// Comparison operation, e.g. x < y
    ComparisonOperation(ComparisonOperation),

    /// Unbox assignment, e.g. *(...) = y, **(...) += y
    UnboxAssignment(UnboxAssignment),
    UnboxSlotAssignment(UnboxSlotAssignment),

    /// Property assignment, e.g. obj.property = value
    PropertyAssignment(PropertyAssignment),

    /// Unary operation, e.g. -x, !x
    UnaryOperation(UnaryOperation),

    /// Apply a value to another value, e.g. function call or type cast
    Apply(Apply),

    /// Call an interface method, e.g. obj->method()
    InterfaceMethodCall(InterfaceMethodCall),

    /// Apply a property access to an argument
    PropertyAccess(PropertyAccess),

    /// Generic instantiation, e.g. MyType<u8>
    GenericInstantiation(GenericInstantiation),

    /// The '?' placeholder expression
    Placeholder(ValueAccessType),

    /// Remote execution, e.g. @example :: 41 + 1
    RemoteExecution(RemoteExecution),

    /// Variant access, e.g. integer/u8
    VariantAccess(VariantAccess),

    EntityValue(EntityValueExpression),
}

impl Spanned for DatexExpressionData {
    type Output = DatexExpression;

    fn with_span<T: Into<ops::Range<usize>>>(self, span: T) -> Self::Output {
        DatexExpression {
            data: Box::new(self),
            span: span.into(),
            ty: None,
        }
    }

    fn with_default_span(self) -> Self::Output {
        DatexExpression {
            data: Box::new(self),
            span: (0..0),
            ty: None,
        }
    }
}

impl Spanned for Box<DatexExpressionData> {
    type Output = DatexExpression;

    fn with_span<T: Into<ops::Range<usize>>>(self, span: T) -> Self::Output {
        DatexExpression {
            data: self,
            span: span.into(),
            ty: None,
        }
    }

    fn with_default_span(self) -> Self::Output {
        DatexExpression {
            data: self,
            span: (0..0),
            ty: None,
        }
    }
}

// directly convert DatexExpression to a ValueContainer
impl TryFrom<&DatexExpressionData> for ValueContainer {
    type Error = ();

    fn try_from(expr: &DatexExpressionData) -> Result<Self, Self::Error> {
        Ok(match expr {
            DatexExpressionData::UnaryOperation(UnaryOperation {
                operator,
                expression,
            }) => {
                let value = ValueContainer::try_from(expression.data())?;
                match value {
                    ValueContainer::Local(Value {
                        inner: CoreValue::Integer(_) | CoreValue::Decimal(_),
                        ..
                    }) => match operator {
                        UnaryOperator::Arithmetic(
                            ArithmeticUnaryOperator::Plus,
                        ) => value,
                        UnaryOperator::Arithmetic(
                            ArithmeticUnaryOperator::Minus,
                        ) => value.neg().map_err(|_| ())?,
                        _ => Err(())?,
                    },
                    _ => Err(())?,
                }
            }
            DatexExpressionData::Null => ValueContainer::Local(Value::null()),
            DatexExpressionData::Boolean(b) => ValueContainer::from(b.clone()),
            DatexExpressionData::Text(s) => ValueContainer::from(s.clone()),
            DatexExpressionData::Decimal(d) => ValueContainer::from(d.clone()),
            DatexExpressionData::Integer(i) => ValueContainer::from(i.clone()),
            DatexExpressionData::TypedInteger(i) => {
                ValueContainer::from(i.clone())
            }
            DatexExpressionData::TypedDecimal(d) => {
                ValueContainer::from(d.clone())
            }
            DatexExpressionData::Endpoint(e) => ValueContainer::from(e.clone()),
            DatexExpressionData::List(list) => {
                let entries = list
                    .items
                    .iter()
                    .map(|e| ValueContainer::try_from(e.data()))
                    .collect::<Result<Vec<ValueContainer>, ()>>()?;
                ValueContainer::from(core_values::list::List::from(entries))
            }
            DatexExpressionData::Map(pairs) => {
                let entries = pairs
                    .entries
                    .iter()
                    .map(|(k, v)| {
                        let key = ValueContainer::try_from(k.data())?;
                        let value = ValueContainer::try_from(v.data())?;
                        Ok((key, value))
                    })
                    .collect::<Result<Vec<(ValueContainer, ValueContainer)>, ()>>()?;
                ValueContainer::from(core_values::map::Map::from(entries))
            }
            _ => Err(())?,
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct BinaryOperation {
    pub operator: BinaryOperator,
    pub left: DatexExpression,
    pub right: DatexExpression,
    pub ty: Option<Type>,
}
impl ToInstructions for BinaryOperation {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::binary_operation(self.operator);
            for instruction in self.left.to_instructions(ctx) {
                yield instruction;
            }
            for instruction in self.right.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct RangeDeclaration {
    pub start: DatexExpression,
    pub end: DatexExpression,
}
impl ToInstructions for RangeDeclaration {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::range();
            for instruction in self.start.to_instructions(ctx) {
                yield instruction;
            }
            for instruction in self.end.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct ComparisonOperation {
    pub operator: ComparisonOperator,
    pub left: DatexExpression,
    pub right: DatexExpression,
}

impl ToInstructions for ComparisonOperation {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::comparison_operation(self.operator);
            for instruction in self.left.to_instructions(ctx) {
                yield instruction;
            }
            for instruction in self.right.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnboxAssignment {
    pub operator: Option<ModificationOperator>,
    pub unbox_expression: DatexExpression,
    pub assigned_expression: DatexExpression,
}
impl ToInstructions for UnboxAssignment {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            match self.operator {
                Some(operator) => match operator {
                    ModificationOperator::AddAssign => {
                        yield RegularInstruction::increment()
                    }
                    ModificationOperator::SubtractAssign => {
                        yield RegularInstruction::decrement()
                    }
                    _ => todo!("Generate x = x * z instructions;"),
                },
                None => yield RegularInstruction::set_shared_container_value(),
            };

            // compile assigned expression
            for instruction in self.assigned_expression.to_instructions(ctx) {
                yield instruction;
            }

            // compile unbox expression
            for instruction in self.unbox_expression.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnboxSlotAssignment {
    pub operator: Option<ModificationOperator>,
    pub stack_index: StackIndex,
    pub assigned_expression: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PropertyAssignment {
    pub operator: Option<ModificationOperator>,
    pub base: DatexExpression,
    pub property: DatexExpression,
    pub assigned_expression: DatexExpression,
}

impl ToInstructions for PropertyAssignment {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            let PropertyAssignment {
                base,
                property,
                assigned_expression,
                ..
            } = self;
            // depending on the key, handle different property assignments

            match &property.data() {
                DatexExpressionData::Text(key)
                    if key.0.len() <= u8::MAX as usize =>
                {
                    yield RegularInstruction::set_entry_text(key.0.clone());
                }

                DatexExpressionData::Integer(index)
                    if let Some(index) = index.as_u32() =>
                {
                    yield RegularInstruction::set_entry_index(index);
                }

                _ => {
                    for instruction in property.to_instructions(ctx) {
                        yield instruction;
                    }
                }
            }
            // compile assigned expression
            for instruction in assigned_expression.to_instructions(ctx) {
                yield instruction;
            }

            // compile base expression
            for instruction in base.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Conditional {
    pub condition: DatexExpression,
    pub then_branch: DatexExpression,
    pub else_branch: Option<DatexExpression>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TypeDeclarationExpression {
    pub id: Option<VariableId>,
    pub name: String, // TODO #614: separate variant from name
    pub definition: TypeExpression,
    pub hoisted: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnaryOperation {
    pub operator: UnaryOperator,
    pub expression: DatexExpression,
}
impl ToInstructions for UnaryOperation {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::unary_operation(self.operator);
            for instruction in self.expression.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq, Default, Hash, Eq)]
pub enum ValueAccessType {
    /// 'mut x
    SharedRefMut,
    /// 'x
    SharedRef,
    /// clone x
    Clone, // TODO: allow clone only for non-shared values, for shared values, do clone *x
    /// temp borrow for x (used before Unbox)
    Borrow,
    #[default]
    MoveOrCopy,
}

impl From<&ReferenceMutability> for ValueAccessType {
    fn from(mutability: &ReferenceMutability) -> Self {
        match mutability {
            ReferenceMutability::Mutable => ValueAccessType::SharedRefMut,
            ReferenceMutability::Immutable => ValueAccessType::SharedRef,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Apply {
    pub base: DatexExpression,
    pub arguments: Vec<DatexExpression>,
}

impl ToInstructions for Apply {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::apply(self.arguments.len() as u8);
            // compile arguments
            for argument in &self.arguments {
                for instruction in argument.to_instructions(ctx) {
                    yield instruction;
                }
            }
            // compile function expression
            for instruction in self.base.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct InterfaceMethodCall {
    pub target: DatexExpression,
    pub method_name: String,
    pub arguments: Vec<DatexExpression>,
}
impl ToInstructions for InterfaceMethodCall {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            // TODO: replace with trait impls
            match self.method_name.as_str() {
                "append" => {
                    yield RegularInstruction::append_entry();

                    for argument in &self.arguments {
                        for instruction in argument.to_instructions(ctx) {
                            yield instruction;
                        }
                    }
                }

                "clear" => {
                    yield RegularInstruction::clear();
                }

                "splice" => {
                    yield RegularInstruction::splice_dynamic();

                    for argument in &self.arguments {
                        for instruction in argument.to_instructions(ctx) {
                            yield instruction;
                        }
                    }
                }

                _ => {
                    yield RegularInstruction::call_method(
                        self.method_name.clone(),
                        self.arguments.len() as u8,
                    );

                    for argument in &self.arguments {
                        for instruction in argument.to_instructions(ctx) {
                            yield instruction;
                        }
                    }
                }
            }

            // compile target expression
            for instruction in self.target.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

impl InterfaceMethodCall {
    pub fn new(
        target: DatexExpression,
        method_name: String,
        arguments: Vec<DatexExpression>,
    ) -> Self {
        InterfaceMethodCall {
            target,
            method_name,
            arguments,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct PropertyAccess {
    pub base: DatexExpression,
    pub property: DatexExpression,
}

impl ToInstructions for PropertyAccess {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            // depending on the key, handle different property accesses
            match self.property.data() {
                // simple text key if length fits in u8
                DatexExpressionData::Text(key) if key.0.len() <= 255 => {
                    yield RegularInstruction::get_entry_text(key.0.clone());
                }
                // index access if integer fits in u32
                DatexExpressionData::Integer(index)
                    if let Some(index) = index.as_u32() =>
                {
                    yield RegularInstruction::get_entry_index(index);
                }
                _ => {
                    yield RegularInstruction::get_entry_dynamic();
                    for instruction in self.property.to_instructions(ctx) {
                        yield instruction;
                    }
                }
            }

            // compile base expression
            for instruction in self.base.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct GenericInstantiation {
    pub base: DatexExpression,
    pub generic_arguments: Vec<TypeExpression>,
}
impl ToInstructions for GenericInstantiation {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            // NOTE: might already be handled in type compilation
            todo!()
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct RemoteExecution {
    pub left: DatexExpression,
    pub right: DatexExpression,
    /// internal metadata set by precompiler, indicates how many variables from parent scope are accessed inside the remote execution
    pub injected_variable_count: Option<u32>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct UnboundedStatement {
    pub is_first: bool,
    pub is_last: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Statements {
    pub statements: Vec<DatexExpression>,
    pub is_terminated: bool,
    pub unbounded: Option<UnboundedStatement>,
}

impl Statements {
    pub fn empty() -> Self {
        Statements {
            statements: Vec::new(),
            is_terminated: true,
            unbounded: None,
        }
    }
    pub fn new_terminated(statements: Vec<DatexExpression>) -> Self {
        Statements {
            statements,
            is_terminated: true,
            unbounded: None,
        }
    }
    pub fn new_unterminated(statements: Vec<DatexExpression>) -> Self {
        Statements {
            statements,
            is_terminated: false,
            unbounded: None,
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariableDeclaration {
    pub id: Option<VariableId>,
    pub kind: VariableKind,
    pub name: String,
    pub type_annotation: Option<TypeExpression>,
    pub init_expression: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariableAssignment {
    pub id: Option<VariableId>,
    pub name: String,
    pub operator: Option<ModificationOperator>,
    pub expression: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityDeclarationExpression {
    pub id: Option<VariableId>,
    pub name: String,
    pub definition: TypeExpression,
    pub hoisted: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CompileExpression {
    pub expression: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariableAccess {
    pub id: VariableId,
    pub name: String,
    pub access_type: ValueAccessType,
}

#[derive(Clone, Debug, PartialEq)]
pub struct RequestSharedRef {
    pub mutability: ReferenceMutability,
    pub address: PointerAddress,
}
impl ToInstructions for RequestSharedRef {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(core::iter::once(RegularInstruction::get_shared_ref(
            self.address.clone(),
            &self.mutability,
        )))
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct CallableDeclaration {
    pub signature: CallableSignature,
    pub body: DatexExpression,
    pub injected_variable_count: Option<u32>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct CallableSignature {
    pub name: Option<String>,
    pub kind: CallableKind,
    pub requires_async: bool,
    pub parameters: Vec<(String, TypeExpression)>,
    pub rest_parameter: Option<(String, TypeExpression)>,
    pub return_type: Option<TypeExpression>,
    pub yeet_type: Option<TypeExpression>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct List {
    pub items: Vec<DatexExpression>,
}
impl ToInstructions for List {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::list(self.items.len() as u32);
            for item in &self.items {
                for instruction in item.to_instructions(ctx) {
                    yield instruction;
                }
            }
        })
    }
}

impl List {
    pub fn new(items: Vec<DatexExpression>) -> Self {
        List { items }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct Map {
    pub entries: Vec<(DatexExpression, DatexExpression)>,
}

impl ToInstructions for Map {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::map(self.entries.len() as u32);
            for (key, value) in &self.entries {
                match &*key.data {
                    // text -> insert key string
                    DatexExpressionData::Text(text) => {
                        if text.len() < 256 {
                            yield RegularInstruction::key_value_short_text(
                                text.0.clone(),
                            );
                        } else {
                            yield RegularInstruction::key_value_dynamic();
                            yield RegularInstruction::text(text.0.clone());
                        }
                    }
                    // other -> insert key as dynamic
                    _ => {
                        yield RegularInstruction::key_value_dynamic();
                        for instruction in key.to_instructions(ctx) {
                            yield instruction;
                        }
                    }
                };

                // value
                for instruction in value.to_instructions(ctx) {
                    yield instruction;
                }
            }
        })
    }
}

impl Map {
    pub fn new(entries: Vec<(DatexExpression, DatexExpression)>) -> Self {
        Map { entries }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum VariableKind {
    Const,
    Var,
}

impl Display for VariableKind {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            VariableKind::Const => core::write!(f, "const"),
            VariableKind::Var => core::write!(f, "var"),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct TagExpression {
    pub tag: String,
    pub expression: Option<DatexExpression>,
}

impl ToInstructions for TagExpression {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::tagged_value(
                self.tag.clone(),
                self.expression.is_none(),
            );
            if let Some(expression) = &self.expression {
                for instruction in expression.to_instructions(ctx) {
                    yield instruction;
                }
            }
        })
    }
}

impl Display for TagExpression {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        core::write!(f, "#{}", self.tag)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct RootPropertyAccess {
    pub property_name: String,
}

impl ToInstructions for RootPropertyAccess {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            let root_property = RootProperty::from_str(&self.property_name)
                .expect("invalid root property name");
            yield RegularInstruction::get_root_property(root_property);
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct StackAssignment {
    pub index: StackIndex,
    pub expression: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct StackListAssignment {
    pub expression: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct VariantAccess {
    pub name: String,
    pub variant: String,
    pub base: ResolvedVariable,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EntityValueExpression {
    pub entity_name: String,
    pub entity_address: Option<PointerAddress>,
    pub value: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Unbox {
    pub expression: DatexExpression,
}

impl ToInstructions for Unbox {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            yield RegularInstruction::unbox();
            for instruction in self.expression.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct CloneExpression {
    pub expression: DatexExpression,
}

#[derive(Clone, Debug, PartialEq)]
pub struct DeriveRef {
    pub mutability: LocalReferenceMutability,
    pub expression: DatexExpression,
}

impl ToInstructions for DeriveRef {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            for instruction in self.expression.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct CreateShared {
    pub mutability: SharedContainerMutability,
    pub expression: DatexExpression,
}

impl ToInstructions for CreateShared {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            match self.mutability {
                SharedContainerMutability::Immutable => {
                    yield RegularInstruction::create_shared();
                }
                SharedContainerMutability::Mutable => {
                    yield RegularInstruction::create_shared_mut();
                }
            }

            for instruction in self.expression.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct DeriveSharedRef {
    pub mutability: ReferenceMutability,
    pub expression: DatexExpression,
}

impl ToInstructions for DeriveSharedRef {
    type InstructionType = RegularInstruction;

    fn to_instructions<'tracking, 'ctx, 'iter>(
        &'iter self,
        ctx: &'iter InstructionContext<'tracking, 'ctx>,
    ) -> Box<impl Iterator<Item = Self::InstructionType> + 'iter> {
        Box::new(gen move {
            match self.mutability {
                ReferenceMutability::Immutable => {
                    yield RegularInstruction::derive_shared_reference();
                }
                ReferenceMutability::Mutable => {
                    yield RegularInstruction::derive_shared_reference_mut();
                }
            }

            for instruction in self.expression.to_instructions(ctx) {
                yield instruction;
            }
        })
    }
}

#[derive(Clone, Debug, PartialEq)]
pub struct CreateMut {
    pub expression: DatexExpression,
}
