//! This module contains various traits that are shared on different levels such as [apply], [identity], [structural_eq] and [value_eq].
pub mod apply;
pub mod callable;
pub mod classification;
pub mod clone_unsafe;
pub mod convert_parts;
pub mod convert_value;
pub mod convert_value_container;
pub mod datex_hash;
pub mod datex_native_only_structural;
pub mod datex_native_structural;
pub mod dyn_eq;
pub mod get_core_lib_type_id;
pub mod get_datex_type;
pub mod identity;
pub mod iter_parts;
pub mod local_child_path_resolver;
pub mod structural_eq;
#[cfg(feature = "ast")]
pub mod to_datex_expression_data;
#[cfg(feature = "ast")]
pub mod to_type_expression_data;
pub mod try_clone;
pub mod value_access;
pub mod value_eq;
