[package]
name = "datex-crypto-esp32"
version = "0.0.3"
description = "Embedded ESP32 target implementation of the DATEX Crypto facade"
authors = [
    "Benedikt Strehle <benedikt@unyt.org>",
    "Jonas Strehle <jonas@unyt.org>",
    "Norbert Brzezinski <norbert@unyt.org>",
]
edition = "2024"
license-file = "LICENSE"


[lib]
crate-type = ["rlib"]

[lints.clippy]
std_instead_of_core = "deny"
alloc_instead_of_core = "deny"
std_instead_of_alloc = "deny"
result_unit_err = "allow"

[dependencies]
datex-crypto-facade = { path = "../datex-crypto-facade", version = "0.0.2" }
spin = "0.10.0"
static_cell = "2.1.1"
esp-hal = { version = "1.0.0", features = [
    "unstable",
    "psram",
], default-features = false }


[features]
esp32 = ["esp-hal/esp32"]
esp32s3 = ["esp-hal/esp32s3"]
esp32c2 = ["esp-hal/esp32c2"]
