[alias]
# Run tests with `std` features with `cargo test-std`
test-std = [
	"test",
	"-p",
	"datex-core",
	"--features",
	"full,target_native",
	"--",
	"--nocapture",
]

# Run tests without `std` features with `cargo test-nostd`
test-nostd = [
	"test",
	"-p",
	"datex-core",
	"--features",
	"full,allow_unsigned_blocks",
	"--",
	"--nocapture",
]

# Run a specific test case with `cargo testcase <test_name>`
testcase = [
	"test",
	"-p",
	"datex-core",
	"--features",
	"full,target_native",
	"--lib",
	"--",
	"--nocapture",
]
